#!/bin/sh

GIT=/usr/bin/git
OPTION="submodule add"

cd ../

$GIT $OPTION https://github.com/vim-scripts/Command-T.git vim/vim/bundle/Command-T
$GIT $OPTION https://github.com/vim-scripts/FuzzyFinder.git vim/vim/bundle/FuzzyFinder
$GIT $OPTION http://github.com/vim-scripts/L9.git vim/vim/bundle/L9
$GIT $OPTION https://github.com/vim-scripts/Tagbar.git vim/vim/bundle/Tagbar
$GIT $OPTION https://github.com/vim-scripts/The-NERD-tree.git vim/vim/bundle/The-NERD-tree
$GIT $OPTION https://github.com/vim-scripts/ZenCoding.vim.git vim/vim/bundle/ZenCoding.vim
$GIT $OPTION https://github.com/vim-scripts/ctrlp.vim.git vim/vim/bundle/ctrlp.vim
$GIT $OPTION https://github.com/vim-scripts/cocoa.vim.git vim/vim/bundle/custom-cocoa.vim
$GIT $OPTION https://github.com/vim-scripts/django.vim.git vim/vim/bundle/django.vim
$GIT $OPTION https://github.com/vim-scripts/pathogen.vim.git vim/vim/bundle/pathogen.vim
$GIT $OPTION https://github.com/rstacruz/sparkup.git vim/vim/bundle/sparkup
$GIT $OPTION https://github.com/Lokaltog/vim-easymotion.git vim/vim/bundle/vim-easymotion
$GIT $OPTION https://github.com/tpope/vim-fugitive.git vim/vim/bundle/vim-fugitive
$GIT $OPTION https://github.com/tpope/vim-rails.git vim/vim/bundle/vim-rails
$GIT $OPTION https://github.com/derekwyatt/vim-scala.git vim/vim/bundle/vim-scala
$GIT $OPTION https://github.com/gmarik/vundle.git vim/vim/bundle/vundle

